[project]
name = "events"
version = "0.0.0"
authors = [
    {name = "Shish", email = "shish@shishnet.org"},
]
description = "An Event Index"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask",
    "flask-sqlalchemy",
    "flask-htmx",
    "icalendar",
    "bcrypt",
]

[dependency-groups]
dev = [
    "ruff",
    "ty",
    "pytest-cov",
]

[tool.setuptools]
py-modules = ["events"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing --cov-fail-under 20"

[tool.coverage.run]
source = ["events"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = [
    "E712",  # sqlalchemy requires "Table.column == True"
]
